{
 "title": "Git Insights",
 "description": "Pull request Insights",
 "tags": [ "git" ],
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Pull Requests Daily Trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  closed,\n  open\nFROM extracted_pull_request_count\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Pull Request Time to Close",
   "type": "gauge",
   "description": "PR Time to Close ",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  pr_created_at AS \"time\",\n  duration\nFROM transformed_pull_request_data\nWHERE\n  $__timeFilter(pr_created_at) AND\n  status = 'closed'\nORDER BY pr_created_at"
    }
   ]
  },
  {
   "title": "Pull Requests Waiting for Review",
   "type": "gauge",
   "description": "Pull Requests Waiting for Review",
   "gridPos": { "h": 7, "w": 5, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  pr_created_at AS \"time\",\n  duration\nFROM transformed_pull_request_data\nWHERE\n  $__timeFilter(pr_created_at) AND\n  status = 'open'\nORDER BY pr_created_at"
    }
   ]
  },
  {
   "title": "Pull Requests Overall Trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  closed,\n  open\nFROM transformed_pull_request_count\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Closed Pull Requests Count ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(pr_created_at,$__interval),\n  count(id) AS \"Count\"\nFROM transformed_pull_request_data\nWHERE\n  $__timeFilter(pr_created_at) AND\n  status = 'closed'\nGROUP BY 1\nORDER BY $__timeGroup(pr_created_at,$__interval)"
    }
   ]
  },
  {
   "title": "Open Pull Requests Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(pr_created_at,$__interval),\n  count(id) AS \"Count\"\nFROM transformed_pull_request_data\nWHERE\n  $__timeFilter(pr_created_at) AND\n  status = 'open'\nGROUP BY 1\nORDER BY $__timeGroup(pr_created_at,$__interval)"
    }
   ]
  }
 ]
}