name: Testing multiple events 

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to deploy
        required: true
jobs:
  deploy:
    name: deploy images
    runs-on: ubuntu-18.04
    steps:
    - run: |
        echo "Hello ${{ github.event.inputs.tag }}!"
