name: Testing multiple events 
env: 
  DEFAULT_TAG: latest
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to deploy
        required: false
        default: latest
jobs:
  deploy:
    name: deploy images
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo $GITHUB_EVENT_NAME
        echo $GITHUB_REF
        echo "Hello ${{ github.event.inputs.tag }}!"
    - run: |
        echo ${{github.event.name }}
