name: Testing multiple events 
env: 
  DEFAULT_TAG: latest
  DEFAULT_TAG2: latest
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to deploy
        required: true
        default: latest
jobs:
  deploy:
    name: deploy images
    runs-on: ubuntu-latest
    steps:
    #if: github.event_name == 'workflow_dispatch'
    - run: |
        echo "DEFAULT_TAG2= $(echo ${{ github.event_name == 'workflow_dispatch' &&  github.event.inputs.tag || env.DEFAULT_TAG }})" >> $GITHUB_ENV
        echo "DEFAULT_TAG=$(echo ${{github.event.inputs.tag}})" >> $GITHUB_ENV
    - run: |
        echo $DEFAULT_TAG
        echo $DEFAULT_TAG2
