name: Testing multiple events 
env: 
  DEFAULT_TAG: latest
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to deploy
        required: false
        default: $DEFAULT_TAG
jobs:
  deploy:
    name: deploy images
    runs-on: ubuntu-18.04
    steps:
    - run: |
        echo "$GITHUB_EVENT_NAME -"
        echo "Hello ${{ github.event.inputs.tag }}!"
